# Generated by Django 4.1.1 on 2022-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.CharField(max_length=5000),
        ),
    ]
