# Generated by Django 4.1.1 on 2022-09-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_clientinfocounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_logo', models.ImageField(default='', upload_to='website/images')),
            ],
        ),
    ]
