# Generated by Django 4.1.1 on 2022-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_member_profession',
            field=models.CharField(default='', max_length=50),
        ),
    ]
