# Generated by Django 4.1.1 on 2022-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_team_team_member_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_member_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
