# Generated by Django 4.1.1 on 2022-09-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_team_team_member_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_member_facebook',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_member_instagram',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_member_linkedin',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_member_stackoverflow',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_member_twitter',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
