# Generated by Django 4.1.1 on 2022-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_team_team_member_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_member_pic',
            field=models.ImageField(blank=True, default='', upload_to='website/images'),
        ),
    ]
